# Test config for decronym 

title = "Decronym Default Config"

[source]
paths = [
]
urls = [
    "https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/ISO-3166-1-alpha-3.json",
    "https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/file_ext.json",
    "https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/tech.json"
    ]

[source.silmaril]
enable = true
uri = "http://acronyms.silmaril.ie/cgi-bin/xaa"
