# Test config for decronym 

title = "Decronym Default Config"

[source]
paths = [
   
]
urls = ["https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/ISO-3166-1-alpha-3.json"
    ]

[source.silmaril]
enable = false
uri = "http://acronyms.silmaril.ie/cgi-bin/xaa"
