title = "Decronym Default Config"

[source]
path = [ "tests/data/valid.json",]
url = [ "https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/ISO-3166-1-alpha-3.json", "https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/file_ext.json", "https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/tech.json",]

[source.misc.timeanddate]
enable = true
url = "https://www.timeanddate.com/time/zones/"

[source.misc.iso_currency]
enable = true
url = "https://www.currency-iso.org/dam/downloads/lists/list_one.xml"

[source.misc.confluence_table]
enable = false
url = "https://internal.confluence.com"
page_id = 0