# Test config for decronym 

title = "Decronym Default Config"

[source]
path = [
]
url = [
    "https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/ISO-3166-1-alpha-3.json",
    "https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/file_ext.json",
    "https://raw.githubusercontent.com/lokraszewski/decronym_json_example/main/tech.json"
    ]

[source.timeanddate]
enable = true
url = "https://www.timeanddate.com/time/zones/"

[source.iso_currency]
enable = true
url = "https://www.currency-iso.org/dam/downloads/lists/list_one.xml"